### ISSUE TITLE
Add support for .jsx files

### ISSUE THREAD

**Issue by dreamawakening** [kamataryo/eslint-snippets#6]
The snippet results should show for JSX files. They're currently only supported for `.js` and `.json`.

**Comment by kamataryo** [comment]
Hello, thanks for the comment.
`.jsx` and new rules for latest ESLint support were supported at new version `v0.1.18`.
https://atom.io/packages/eslint-snippets

**Comment by dreamawakening** [comment]
Great response time, cheers.

**Comment by dreamawakening** [comment]
Also, I thought I'd point out that the README still needs to mention `.jsx`:

> gThe snippets are available on *.js or *.json.

And the "g" is a typo.

**Comment by kamataryo** [comment]
@mightyspaj Exactly, Thanks a lot!
