### ISSUE TITLE
[Feature request] Make eslint results less prominent (and/or require prefix?)

### ISSUE THREAD

**Issue by timmfin** [kamataryo/eslint-snippets#8]
Having snippets for eslint rules is helpful, but it is a bit of a bummer that they eagerly take precedence over other variable names in my script:

![image](https://user-images.githubusercontent.com/60455/38736753-0a1e9294-3efb-11e8-97ad-40a135eefc8a.png)

Is there anyway to get those eslint results to show up at the bottom of the popup menu (unless much more specifically matched)? Or if that isn't an option, maybe it would be worthwhile to only show the eslint snippets if some prefix, like `eslint` has been typed?

**Comment by kamataryo** [comment]
Hi, thanks for the feedback.
I agree that they are messy and excessive.
New released [v0.4.1](https://atom.io/packages/eslint-snippets) simply eliminates all `eslint-disable* {{rule-names}}` completions.
Consequently variable name will be prior to rule name suggestions.
